_target_: gatr.experiments.symmetry.wrappers.SymmetryTransformerWrapper

net:
  _target_: gatr.baselines.BaselineTransformer

  in_channels: 3
  out_channels: 1
  hidden_channels: 128

  num_blocks: 12
  num_heads: 8

  pos_encoding: false
